
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class Share extends javax.swing.JFrame {

    /**
     * Creates new form Share
     */
    public Share() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jButton1 = new javax.swing.JButton();
        save = new javax.swing.JButton();
        browse = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().setLayout(null);

        save.setBackground(new java.awt.Color(0, 102, 102));
        save.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(20, 500, 370, 40);

        browse.setBackground(new java.awt.Color(0, 102, 102));
        browse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        browse.setText("Browse");
        browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseActionPerformed(evt);
            }
        });
        getContentPane().add(browse);
        browse.setBounds(20, 450, 370, 40);

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setLayout(null);
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 10, 350, 350);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setText("Name File");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 364, 360, 20);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(20, 50, 370, 390);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 0));
        jTextField1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jTextField1.setText("UPLOAD PICT");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(20, 10, 280, 30);

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("TUTUP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 10, 90, 30);

        setBounds(0, 0, 428, 591);
    }// </editor-fold>//GEN-END:initComponents

    private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed
        JFileChooser chooser = new JFileChooser();
           chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
           // we will filter the images
           // Setting up a File Filter
           chooser.setFileFilter(new FileFilter(){               
               @Override
               public String getDescription() {
                   //return "Portable Network Graphics (*.png)"; // its for .png image file
                   return "All image Support!";
               }
               
               @Override
               public boolean accept(File f) {
                   if (f.isDirectory()) {
                       return true;
                   } else {
                       return f.getName().toLowerCase().endsWith(".png")
                               || f.getName().toLowerCase().endsWith(".jpeg")
                               || f.getName().toLowerCase().endsWith(".jpg")
                               || f.getName().toLowerCase().endsWith(".gif"); // lets try it
                   }
               }
                // how we can do for all images suport?
               // lets do it           
           });
           
           int res = chooser.showOpenDialog(Share.this);
           if (res== JFileChooser.APPROVE_OPTION){
               File file = chooser.getSelectedFile();               
               // Creating ImageIcon out of the selected file
               ImageIcon image = new ImageIcon(file.getAbsolutePath());
               // Get width and height of picLabel
               Rectangle rect = jLabel1.getBounds();
               // Scaling the Image to fit in the picLabel
               Image scaledimage = image.getImage().getScaledInstance(rect.width,rect.height,Image.SCALE_DEFAULT);
               // Converting the image back to ImageIcon to make it acceptable by picLabel
               image = new ImageIcon(scaledimage);
               jLabel1.setIcon(image); // lets try it!               
               // we will show the name of file to JLabel2
               String name = file.getName();
               jLabel2.setText(name);
               
           } else {
               JOptionPane.showMessageDialog(this,"Cancelled by user!");
           }           
        // TODO add your handling code here:
    }//GEN-LAST:event_browseActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
         // now e can coding for save dialog
        Rectangle rec = jPanel3.getBounds();
        BufferedImage badge = new BufferedImage(rec.width,rec.height,BufferedImage.TYPE_INT_ARGB);
        jPanel3.paint(badge.getGraphics());
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int res = chooser.showSaveDialog(Share.this);
        
        if (res == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            
            try {
                // Writing the captured area to a png image
                ImageIO.write(badge,"png",file);
                JOptionPane.showMessageDialog(Share.this,"The images was saved successFully!","Success",JOptionPane.INFORMATION_MESSAGE);                       
                                
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(Share.this,"The images was saved successFully!","ERROR",JOptionPane.ERROR_MESSAGE);                 
            }            
        } else {
            JOptionPane.showMessageDialog(this,"Cancelled by user !");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Share.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Share.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Share.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Share.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Share().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browse;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
